# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Its Mike'
tagline:          'Blog by Michael Schilling'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'Developer at Move4Mobile working on Web Platform'
url:              http://michaelschilling.com
baseurl:          /

author:
  name:           'Michael Schilling'
  url:            https://twitter.com/mschilling

paginate:         5

# Custom vars
version:          0.0.1-SNAPSHOT

github:
  repo:           https://github.com/mschilling/mschilling.github.io
